# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoGoLook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for GoGoLook

  target 'GoGoLookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoGoLookUITests' do
    # Pods for testing
  end

end
